version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - csv-volume:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
  
  backend:
    build:
      context: ./Backend
    ports:
      - "8081:8080"
    depends_on:
      - db
  
  frontend:
    build:
      context: ./Frontend
    ports:
      - "3000:3000"

volumes:
  csv-volume:
